---
- name: Create app stack directory
  file:
    path: /opt/app_stack
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Create web network in Docker
  community.docker.docker_network:
    name: web
    state: present

- name: Copy app stack docker-compose file
  copy:
    src: docker-compose.yml
    dest: /opt/app_stack/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Start application stack using Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/app_stack
    state: present
