---
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure Docker group exists
  group:
    name: docker
    state: present

- name: Get all user accounts
  getent:
    database: passwd

- name: Add all regular users to Docker group
  user:
    name: "{{ item.key }}"
    groups: docker
    append: yes
  loop: "{{ getent_passwd | dict2items }}"
  when: 
    - (item.value[1] | int) >= 1000
    - (item.value[1] | int) < 60000
    - "'nologin' not in item.value[5]"
    - "'false' not in item.value[5]"

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Reset ssh connection to allow user changes to affect docker commands
  meta: reset_connection
